#!/usr/bin/env bash

# Show commits in remote not yet pulled

branch=$(git branch --show-current 2>/dev/null)
if [[ -z "$branch" ]]; then
  echo "Not on a branch"
  exit 1
fi

git fetch origin $branch 2>/dev/null
echo "Commits in origin/$branch not yet pulled:"
git log $branch..origin/$branch --oneline --graph
